version: '2'
services:
  jenkins:
    image: jenkinsci/blueocean
    privileged: true
    environment:
      - JAVA_OPTS=-Djenkins.install.runSetupWizard=false
      - JENKINS_ADMIN_ID=admin
      - JENKINS_ADMIN_PASSWORD=admin
    user: root
    ports:
      - "8080:8080"
      - "50000:50000"
    networks:
      - jenkins
    volumes:
      - jenkinsvol:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock

  # postgres:
  #   image: postgres:9.6
  #   networks:
  #     - jenkins
  #   environment:
  #     POSTGRES_USER: sonar
  #     POSTGRES_PASSWORD: sonarpasswd
  #   volumes_from:
  #     - datadb

  # datadb:
  #   image: postgres
  #   container_name: plugins_postgres
  #   volumes:
  #     - /var/lib/postgresql
  #   command: /bin/true

  nexus:
    image: sonatype/nexus
    container_name: nexus
    privileged: true
    user: root
    networks:
      - jenkins
    volumes:
      - "nexus-data:/nexus-data"
    ports:
      - "8081:8081"
    expose:
      - "8081"

  # sonarqube:
  #   image: sonarqube:lts
  #   ports:
  #     - "9000:9000"
  #     - "9092:9092"
  #   networks:
  #     - jenkins
  #   environment:
  #     SONARQUBE_JDBC_USERNAME: sonar
  #     SONARQUBE_JDBC_PASSWORD: sonarpasswd
  #     SONARQUBE_JDBC_URL: "jdbc:postgresql://postgres:5432/sonar"
  #   depends_on:
  #     - postgres

  tomcat:
     image: bitnami/tomcat:7
     privileged: true
     user: root
     networks:
       - jenkins
     environment:
        - TOMCAT_USERNAME=tomcat
        - TOMCAT_PASSWORD=tomcat
     ports:
       - "8083:8083"
     expose:
       - "8083"
     volumes:
       - ./tomcat:/bitnami/tomcat

networks:
  jenkins:

volumes:
    jenkinsvol: {}
    nexus-data: {}
